APT::FTPArchive::Release {
  Origin "GBfdHenr";
  Label "GBfdHenr APT Repository";
  Suite "stable";
  Codename "gbfdhenr";
  Architectures "amd64";
  Components "main";
  Description "GBfdHenr APT Repository";
};
